'use client';

import { useEffect, useState } from 'react';
import { FileText, Download, Printer, Plus, Sparkles, CheckCircle2 } from 'lucide-react';
import { PageHeader, SectionCard, LoadingState } from '@/components/freightiq/common';
import { ReportCard } from '@/components/freightiq/report-card';
import { Button } from '@/components/ui/button';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from '@/components/ui/dialog';
import { api } from '@/lib/api';
import type { ReportInfo } from '@/lib/types';

import { reports as mockReports } from '@/lib/mock-data';

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportInfo[]>(mockReports);
  const [selected, setSelected] = useState<ReportInfo | null>(null);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    api.getReports().then((data) => {
      setReports(data);
    });
  }, []);

  const handleView = (report: ReportInfo) => {
    setSelected(report);
    setOpen(true);
  };

  const handleDownload = (report: ReportInfo) => {
    const content = [
      '================================================================================',
      `FREIGHTIQ INTELLIGENCE REPORT: ${report.title.toUpperCase()}`,
      'Ministry of Steel / Bulk Cargo Procurement Advisory (SIH26006)',
      '================================================================================',
      `Type: ${report.type}`,
      `Trade Corridor: ${report.route}`,
      `Generated Date: ${report.generatedDate}`,
      `Status: ${report.status.toUpperCase()}`,
      '',
      '--------------------------------------------------------------------------------',
      'EXECUTIVE SUMMARY',
      '--------------------------------------------------------------------------------',
      report.summary,
      '',
      ...report.sections.flatMap((section) => [
        '--------------------------------------------------------------------------------',
        section.heading.toUpperCase(),
        '--------------------------------------------------------------------------------',
        section.content,
        '',
      ]),
      '================================================================================',
      'Generated by FreightIQ Intelligent Decision Support System',
      '================================================================================',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${report.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  const handleGenerateNewReport = () => {
    setGenerating(true);
    setTimeout(() => {
      const newReport: ReportInfo = {
        id: `rep_${Date.now()}`,
        title: 'East Coast Bulk Procurement & Charter Advisory (Q4 Update)',
        type: 'Procurement Strategy',
        route: 'Newcastle / Gladstone ➔ Visakhapatnam & Paradip',
        generatedDate: new Date().toISOString().split('T')[0],
        status: 'ready',
        summary: 'Comprehensive analysis of forward freight trajectories, vessel matching optimization, and Time Charter hedging recommendations for upcoming coking coal import cycles.',
        sections: [
          {
            heading: 'Executive Summary',
            content: 'Forward rate models project a 6.2% to 14.6% increase in Pacific dry bulk freight rates over the next 90 days. High capacity utilization at Visakhapatnam and Paradip ports requires strict draft compliance to eliminate demurrage liabilities.',
          },
          {
            heading: 'Port Constraints & Draft Compliance',
            content: 'Visakhapatnam (Outer Harbour: 18.1m) and Dhamra (18.5m) remain optimal for Capesize bulk carriers. Paradip is suitable for Panamax/Kamsarmax with high-tide windows. Haldia remains draft-restricted to Handysize and lightened vessels.',
          },
          {
            heading: 'Vessel Chartering Recommendation',
            content: 'Recommended procurement strategy is a Hybrid Model (60% 1-Year Time Charter + 40% Spot Market fixtures). This strategy yields an estimated annual savings of $1.15M while insulating blast furnace feedstock supply from spot rate spikes.',
          },
        ],
      };
      setReports((prev) => [newReport, ...prev]);
      setGenerating(false);
      setSelected(newReport);
      setOpen(true);
    }, 800);
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <LoadingState message="Loading intelligence reports..." />;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Procurement & Freight Intelligence Reports"
        subtitle="Download, export, and generate executive reports for the Ministry of Steel & plant logistics managers"
      >
        <Button onClick={handleGenerateNewReport} disabled={generating} className="gap-2 bg-primary hover:bg-primary/90 text-primary-foreground">
          <Sparkles className="h-4 w-4" />
          {generating ? 'Compiling Report...' : 'Generate New Advisory Report'}
        </Button>
      </PageHeader>

      <SectionCard title={`Available Advisory Reports (${reports.length})`}>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {reports.map((report) => (
            <ReportCard key={report.id} report={report} onView={handleView} onDownload={handleDownload} />
          ))}
        </div>
      </SectionCard>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto bg-card border-border">
          {selected && (
            <>
              <DialogHeader>
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                      <FileText className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <DialogTitle className="text-base font-bold text-foreground">{selected.title}</DialogTitle>
                      <p className="text-xs text-muted-foreground mt-0.5">{selected.route} · {selected.generatedDate}</p>
                    </div>
                  </div>
                </div>
              </DialogHeader>

              <div className="space-y-5 mt-4">
                {/* Executive Summary highlight */}
                <div className="rounded-lg border border-primary/30 bg-primary/5 p-4">
                  <h3 className="text-sm font-semibold text-primary mb-2 flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-primary" />
                    Executive Summary
                  </h3>
                  <p className="text-sm text-foreground/90 leading-relaxed font-medium">
                    {selected.summary}
                  </p>
                </div>

                {/* All sections */}
                {selected.sections
                  .filter((s) => s.heading !== 'Executive Summary')
                  .map((section, i) => (
                    <div key={i} className="rounded-lg border border-border/50 p-4 space-y-1.5">
                      <h3 className="text-sm font-bold text-foreground">{section.heading}</h3>
                      <p className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line">
                        {section.content}
                      </p>
                    </div>
                  ))}

                {/* Actions */}
                <div className="flex gap-2 border-t border-border/50 pt-4">
                  <Button variant="default" size="sm" className="gap-2" onClick={() => handleDownload(selected)}>
                    <Download className="h-3.5 w-3.5" />
                    Download Official Report (.txt)
                  </Button>
                  <Button variant="outline" size="sm" className="gap-2" onClick={handlePrint}>
                    <Printer className="h-3.5 w-3.5" />
                    Print / Export PDF
                  </Button>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
