import type {
  FreightRatePoint,
  RouteInfo,
  PortInfo,
  VesselInfo,
  RiskFactor,
  RiskTrendPoint,
  MarketInsight,
  ForecastFactor,
  ReportInfo,
  KpiData,
  MarketEntryRecommendation,
  EarlyWarningAlert,
  IdleScenario,
  RecommendationHistoryItem,
} from '@/lib/types';

export const dashboardKpis: KpiData[] = [
  { label: 'Current Freight Rate', value: '$27.40', unit: '/ MT', change: '+2.1%', trend: 'increasing' },
  { label: '30-Day Forecast', value: '$29.10', unit: '/ MT', change: '+6.2%', trend: 'increasing' },
  { label: 'Market Timing', value: '7–10 Days', unit: 'Window', change: 'Entry Recommended', trend: 'increasing' },
  { label: 'Avg Port Congestion', value: '54.2 hrs', unit: 'Wait', change: 'East Coast India', trend: 'increasing', risk: 'medium' },
  { label: 'Multi-Voyage Savings', value: '11.8%', unit: 'vs Spot', change: 'Proactive Charter', risk: 'low' },
];

export const freightRateData: FreightRatePoint[] = [
  { date: 'Jul 1', historical: 24.80, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Jul 8', historical: 25.10, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Jul 15', historical: 24.90, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Jul 22', historical: 25.60, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Jul 29', historical: 26.10, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Aug 5', historical: 25.80, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Aug 12', historical: 26.40, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Aug 19', historical: 26.90, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Aug 26', historical: 27.10, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Sep 2', historical: 27.40, forecast: null, upperBound: null, lowerBound: null },
  { date: 'Sep 9', historical: null, forecast: 27.65, upperBound: 28.80, lowerBound: 26.50 },
  { date: 'Sep 16', historical: null, forecast: 27.90, upperBound: 29.20, lowerBound: 26.60 },
  { date: 'Sep 23', historical: null, forecast: 28.10, upperBound: 29.60, lowerBound: 26.60 },
  { date: 'Sep 30', historical: null, forecast: 28.45, upperBound: 30.10, lowerBound: 26.80 },
  { date: 'Oct 7', historical: null, forecast: 28.70, upperBound: 30.50, lowerBound: 26.90 },
  { date: 'Oct 14', historical: null, forecast: 29.10, upperBound: 31.00, lowerBound: 27.20 },
  { date: 'Oct 21', historical: null, forecast: 29.30, upperBound: 31.40, lowerBound: 27.20 },
  { date: 'Oct 28', historical: null, forecast: 29.50, upperBound: 31.80, lowerBound: 27.20 },
  { date: 'Nov 4', historical: null, forecast: 29.80, upperBound: 32.20, lowerBound: 27.40 },
  { date: 'Nov 11', historical: null, forecast: 30.10, upperBound: 32.70, lowerBound: 27.50 },
  { date: 'Nov 18', historical: null, forecast: 30.30, upperBound: 33.10, lowerBound: 27.50 },
  { date: 'Nov 25', historical: null, forecast: 30.60, upperBound: 33.60, lowerBound: 27.60 },
  { date: 'Dec 2', historical: null, forecast: 30.90, upperBound: 34.10, lowerBound: 27.70 },
  { date: 'Dec 9', historical: null, forecast: 31.20, upperBound: 34.60, lowerBound: 27.80 },
  { date: 'Dec 16', historical: null, forecast: 31.40, upperBound: 35.10, lowerBound: 27.70 },
];

export const routes: RouteInfo[] = [
  {
    id: 'r1',
    origin: 'Australia',
    originPort: 'Newcastle',
    destination: 'India',
    destinationPort: 'Paradip',
    currentRate: 27.40,
    forecastRate: 29.10,
    trend: 'increasing',
    risk: 'medium',
    distance: 5200,
    duration: 21,
    congestion: 'high',
    coordinates: { origin: [-32.92, 151.78], destination: [20.27, 86.71] },
  },
  {
    id: 'r2',
    origin: 'Australia',
    originPort: 'Newcastle',
    destination: 'India',
    destinationPort: 'Visakhapatnam',
    currentRate: 26.80,
    forecastRate: 28.50,
    trend: 'increasing',
    risk: 'medium',
    distance: 5350,
    duration: 22,
    congestion: 'medium',
    coordinates: { origin: [-32.92, 151.78], destination: [17.69, 83.28] },
  },
  {
    id: 'r3',
    origin: 'Australia',
    originPort: 'Gladstone',
    destination: 'India',
    destinationPort: 'Gangavaram',
    currentRate: 26.20,
    forecastRate: 27.90,
    trend: 'stable',
    risk: 'low',
    distance: 5400,
    duration: 22,
    congestion: 'low',
    coordinates: { origin: [-23.85, 151.27], destination: [17.68, 83.25] },
  },
  {
    id: 'r4',
    origin: 'Australia',
    originPort: 'Hay Point',
    destination: 'India',
    destinationPort: 'Dhamra',
    currentRate: 25.90,
    forecastRate: 27.40,
    trend: 'increasing',
    risk: 'low',
    distance: 5150,
    duration: 20,
    congestion: 'low',
    coordinates: { origin: [-21.28, 149.30], destination: [20.82, 86.96] },
  },
  {
    id: 'r5',
    origin: 'Indonesia',
    originPort: 'Muara Pantai',
    destination: 'India',
    destinationPort: 'Paradip',
    currentRate: 14.80,
    forecastRate: 15.60,
    trend: 'increasing',
    risk: 'low',
    distance: 2850,
    duration: 11,
    congestion: 'medium',
    coordinates: { origin: [2.18, 117.60], destination: [20.27, 86.71] },
  },
  {
    id: 'r6',
    origin: 'Mozambique',
    originPort: 'Maputo',
    destination: 'India',
    destinationPort: 'Visakhapatnam',
    currentRate: 21.40,
    forecastRate: 22.80,
    trend: 'stable',
    risk: 'medium',
    distance: 4400,
    duration: 18,
    congestion: 'medium',
    coordinates: { origin: [-25.97, 32.58], destination: [17.69, 83.28] },
  },
  {
    id: 'r7',
    origin: 'USA',
    originPort: 'Baltimore',
    destination: 'India',
    destinationPort: 'Paradip',
    currentRate: 48.50,
    forecastRate: 51.20,
    trend: 'increasing',
    risk: 'high',
    distance: 9800,
    duration: 38,
    congestion: 'high',
    coordinates: { origin: [39.29, -76.61], destination: [20.27, 86.71] },
  },
  {
    id: 'r8',
    origin: 'Russia',
    originPort: 'Taman / Ust-Luga',
    destination: 'India',
    destinationPort: 'Haldia',
    currentRate: 42.00,
    forecastRate: 44.50,
    trend: 'increasing',
    risk: 'high',
    distance: 8200,
    duration: 32,
    congestion: 'medium',
    coordinates: { origin: [59.65, 28.25], destination: [22.03, 88.06] },
  },
];

// Authoritative Ports Database (Loading Ports + Indian East Coast Discharge Ports)
export const ports: PortInfo[] = [
  // --- INDIAN EAST COAST DISCHARGE PORTS ---
  {
    id: 'p_paradip',
    name: 'Paradip',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'high',
    maxDraft: 17.1,
    maxLOA: 260,
    maxBeam: 43,
    maxDWT: 125000,
    cargoHandlingRate: 28000, // MT / day
    berthCapacity: 16,
    avgWaitTime: 3.2,
    avgWaitTimeHours: 76.8,
    waitingVesselsCount: 14,
    berthUtilizationPct: 92,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax'],
    coordinates: [20.27, 86.71],
    location: 'Odisha, East Coast India',
    source: 'Paradip Port Authority (PPT) Live Telemetry',
    lastUpdated: '15 mins ago',
  },
  {
    id: 'p_vizag',
    name: 'Visakhapatnam',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'medium',
    maxDraft: 16.5,
    maxLOA: 280,
    maxBeam: 45,
    maxDWT: 150000,
    cargoHandlingRate: 32000,
    berthCapacity: 24,
    avgWaitTime: 2.1,
    avgWaitTimeHours: 50.4,
    waitingVesselsCount: 8,
    berthUtilizationPct: 78,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [17.69, 83.28],
    location: 'Andhra Pradesh, East Coast India',
    source: 'Visakhapatnam Port Authority (VPA)',
    lastUpdated: '25 mins ago',
  },
  {
    id: 'p_gangavaram',
    name: 'Gangavaram',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'low',
    maxDraft: 21.0,
    maxLOA: 330,
    maxBeam: 55,
    maxDWT: 200000,
    cargoHandlingRate: 45000,
    berthCapacity: 9,
    avgWaitTime: 0.8,
    avgWaitTimeHours: 19.2,
    waitingVesselsCount: 3,
    berthUtilizationPct: 58,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [17.68, 83.25],
    location: 'Andhra Pradesh, East Coast India',
    source: 'Gangavaram Port Marine Control',
    lastUpdated: '10 mins ago',
  },
  {
    id: 'p_dhamra',
    name: 'Dhamra',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'low',
    maxDraft: 18.5,
    maxLOA: 320,
    maxBeam: 50,
    maxDWT: 180000,
    cargoHandlingRate: 40000,
    berthCapacity: 6,
    avgWaitTime: 1.2,
    avgWaitTimeHours: 28.8,
    waitingVesselsCount: 4,
    berthUtilizationPct: 64,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [20.82, 86.96],
    location: 'Odisha, East Coast India',
    source: 'Dhamra Port Operations (DPCL)',
    lastUpdated: '1 hour ago',
  },
  {
    id: 'p_gopalpur',
    name: 'Gopalpur',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'low',
    maxDraft: 14.5,
    maxLOA: 230,
    maxBeam: 36,
    maxDWT: 75000,
    cargoHandlingRate: 20000,
    berthCapacity: 4,
    avgWaitTime: 0.9,
    avgWaitTimeHours: 21.6,
    waitingVesselsCount: 2,
    berthUtilizationPct: 45,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax'],
    coordinates: [19.26, 84.91],
    location: 'Odisha, East Coast India',
    source: 'Gopalpur Ports Limited',
    lastUpdated: '2 hours ago',
  },
  {
    id: 'p_haldia',
    name: 'Haldia',
    country: 'India',
    portType: 'discharge',
    status: 'restricted',
    congestion: 'high',
    maxDraft: 8.5, // Riverine tidal constraint
    maxLOA: 230,
    maxBeam: 32,
    maxDWT: 45000,
    cargoHandlingRate: 15000,
    berthCapacity: 14,
    avgWaitTime: 4.8,
    avgWaitTimeHours: 115.2,
    waitingVesselsCount: 16,
    berthUtilizationPct: 96,
    vesselCompatibility: ['Handysize'],
    coordinates: [22.03, 88.06],
    location: 'West Bengal, East Coast India',
    source: 'Syama Prasad Mookerjee Port Kolkata',
    lastUpdated: '30 mins ago',
  },
  {
    id: 'p_sandheads',
    name: 'Sagar-Sandheads',
    country: 'India',
    portType: 'discharge',
    status: 'operational',
    congestion: 'medium',
    maxDraft: 16.0,
    maxLOA: 280,
    maxBeam: 45,
    maxDWT: 120000,
    cargoHandlingRate: 22000,
    berthCapacity: 2,
    avgWaitTime: 2.5,
    avgWaitTimeHours: 60.0,
    waitingVesselsCount: 5,
    berthUtilizationPct: 70,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax'],
    coordinates: [21.50, 88.00],
    location: 'Bay of Bengal Transshipment Point',
    source: 'KoPT Anchorage Dispatch',
    lastUpdated: '4 hours ago',
  },

  // --- OVERSEAS BULK LOADING PORTS ---
  {
    id: 'p_newcastle',
    name: 'Newcastle',
    country: 'Australia',
    portType: 'loading',
    status: 'operational',
    congestion: 'medium',
    maxDraft: 15.2,
    maxLOA: 300,
    maxBeam: 50,
    maxDWT: 180000,
    cargoHandlingRate: 65000,
    berthCapacity: 8,
    avgWaitTime: 2.2,
    avgWaitTimeHours: 52.8,
    waitingVesselsCount: 11,
    berthUtilizationPct: 82,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [-32.92, 151.78],
    location: 'New South Wales, Australia',
    source: 'Port of Newcastle Authority',
    lastUpdated: '1 hour ago',
  },
  {
    id: 'p_gladstone',
    name: 'Gladstone',
    country: 'Australia',
    portType: 'loading',
    status: 'operational',
    congestion: 'low',
    maxDraft: 17.5,
    maxLOA: 315,
    maxBeam: 54,
    maxDWT: 220000,
    cargoHandlingRate: 70000,
    berthCapacity: 6,
    avgWaitTime: 1.1,
    avgWaitTimeHours: 26.4,
    waitingVesselsCount: 4,
    berthUtilizationPct: 62,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [-23.85, 151.27],
    location: 'Queensland, Australia',
    source: 'Gladstone Ports Corporation',
    lastUpdated: '2 hours ago',
  },
  {
    id: 'p_haypoint',
    name: 'Hay Point / Dalrymple Bay',
    country: 'Australia',
    portType: 'loading',
    status: 'operational',
    congestion: 'medium',
    maxDraft: 18.5,
    maxLOA: 330,
    maxBeam: 55,
    maxDWT: 230000,
    cargoHandlingRate: 85000,
    berthCapacity: 7,
    avgWaitTime: 2.6,
    avgWaitTimeHours: 62.4,
    waitingVesselsCount: 9,
    berthUtilizationPct: 88,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [-21.28, 149.30],
    location: 'Mackay, Queensland, Australia',
    source: 'North Queensland Bulk Ports',
    lastUpdated: '45 mins ago',
  },
  {
    id: 'p_baltimore',
    name: 'Baltimore / Norfolk',
    country: 'USA',
    portType: 'loading',
    status: 'operational',
    congestion: 'high',
    maxDraft: 15.5,
    maxLOA: 300,
    maxBeam: 48,
    maxDWT: 160000,
    cargoHandlingRate: 45000,
    berthCapacity: 5,
    avgWaitTime: 3.5,
    avgWaitTimeHours: 84.0,
    waitingVesselsCount: 12,
    berthUtilizationPct: 90,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [39.29, -76.61],
    location: 'Maryland / Virginia, USA',
    source: 'US East Coast Port Dispatch',
    lastUpdated: '3 hours ago',
  },
  {
    id: 'p_maputo',
    name: 'Maputo / Beira',
    country: 'Mozambique',
    portType: 'loading',
    status: 'operational',
    congestion: 'medium',
    maxDraft: 14.2,
    maxLOA: 250,
    maxBeam: 40,
    maxDWT: 90000,
    cargoHandlingRate: 25000,
    berthCapacity: 4,
    avgWaitTime: 2.8,
    avgWaitTimeHours: 67.2,
    waitingVesselsCount: 6,
    berthUtilizationPct: 75,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax'],
    coordinates: [-25.97, 32.58],
    location: 'Maputo Bay, Mozambique',
    source: 'MPDC Marine Ops',
    lastUpdated: '2 hours ago',
  },
  {
    id: 'p_muara',
    name: 'Muara Pantai / Tanjung Bara',
    country: 'Indonesia',
    portType: 'loading',
    status: 'operational',
    congestion: 'low',
    maxDraft: 16.0,
    maxLOA: 290,
    maxBeam: 45,
    maxDWT: 150000,
    cargoHandlingRate: 50000,
    berthCapacity: 6,
    avgWaitTime: 1.4,
    avgWaitTimeHours: 33.6,
    waitingVesselsCount: 5,
    berthUtilizationPct: 60,
    vesselCompatibility: ['Handysize', 'Supramax', 'Panamax', 'Capesize'],
    coordinates: [2.18, 117.60],
    location: 'East Kalimantan, Indonesia',
    source: 'Kaltim Port Authority',
    lastUpdated: '1 hour ago',
  },
];

export const vessels: VesselInfo[] = [
  {
    id: 'v_panamax_1',
    name: 'MV Ocean Pioneer',
    type: 'Panamax',
    capacity: 75000,
    draft: 14.2,
    loa: 225,
    beam: 32.2,
    speed: 13.8,
    availability: 'Immediate',
    status: 'available',
    location: 'Bay of Bengal',
    dailyFuelConsumptionMT: 28.5,
    dailyCharterRateUSD: 16500,
  },
  {
    id: 'v_capesize_1',
    name: 'MV Bharat Gaurav',
    type: 'Capesize',
    capacity: 180000,
    draft: 17.8,
    loa: 292,
    beam: 45.0,
    speed: 14.5,
    availability: 'Oct 15, 2026',
    status: 'on-voyage',
    location: 'Indian Ocean',
    dailyFuelConsumptionMT: 48.0,
    dailyCharterRateUSD: 24500,
  },
  {
    id: 'v_supramax_1',
    name: 'MV Kalinga Express',
    type: 'Supramax',
    capacity: 58000,
    draft: 12.8,
    loa: 199,
    beam: 32.2,
    speed: 13.5,
    availability: 'Immediate',
    status: 'available',
    location: 'Off Paradip',
    dailyFuelConsumptionMT: 24.0,
    dailyCharterRateUSD: 14200,
  },
  {
    id: 'v_handysize_1',
    name: 'MV Sagar Shakti',
    type: 'Handysize',
    capacity: 35000,
    draft: 10.2,
    loa: 180,
    beam: 28.4,
    speed: 13.0,
    availability: 'Oct 18, 2026',
    status: 'in-port',
    location: 'Haldia Anchorage',
    dailyFuelConsumptionMT: 18.0,
    dailyCharterRateUSD: 11500,
  },
  {
    id: 'v_panamax_2',
    name: 'MV Steel Trader',
    type: 'Panamax',
    capacity: 76000,
    draft: 14.3,
    loa: 225,
    beam: 32.2,
    speed: 14.0,
    availability: 'Oct 22, 2026',
    status: 'available',
    location: 'Singapore Strait',
    dailyFuelConsumptionMT: 29.0,
    dailyCharterRateUSD: 16800,
  },
  {
    id: 'v_capesize_2',
    name: 'MV Eastern Splendor',
    type: 'Capesize',
    capacity: 175000,
    draft: 17.5,
    loa: 289,
    beam: 45.0,
    speed: 14.2,
    availability: 'Nov 02, 2026',
    status: 'on-voyage',
    location: 'Malacca Strait',
    dailyFuelConsumptionMT: 46.5,
    dailyCharterRateUSD: 23800,
  },
];

export const marketEntryRecommendations: MarketEntryRecommendation[] = [
  {
    id: 'mer_1',
    route: 'Newcastle, AU → Paradip / Vizag',
    vesselType: 'Panamax',
    cargoQuantity: 75000,
    currentRate: 27.40,
    forecastRate30d: 29.10,
    forecastRate60d: 29.98,
    entryWindow: 'Next 7–10 Days (Optimal)',
    strategy: 'Lock 3-Month Short-Term Multiple-Voyage Charter',
    marketDirection: 'increasing',
    confidence: 84,
    confidenceLevel: 'HIGH',
    reason: 'Freight benchmarks projected to rise by +8.4% due to seasonal Q4 Indian steel mill stocking and firming bunker curves. Securing a 3-voyage commitment now hedges against $127k spot rate variance.',
    createdAt: '2026-10-05',
  },
  {
    id: 'mer_2',
    route: 'Gladstone, AU → Gangavaram / Dhamra',
    vesselType: 'Capesize',
    cargoQuantity: 165000,
    currentRate: 25.80,
    forecastRate30d: 27.20,
    forecastRate60d: 28.50,
    entryWindow: 'Next 12–15 Days',
    strategy: 'Execute 6-Month Medium-Term Charter Package',
    marketDirection: 'increasing',
    confidence: 81,
    confidenceLevel: 'HIGH',
    reason: 'Iron ore and metallurgical coking coal demand steady. Deepwater discharge at Gangavaram avoids Paradip draft lightering penalties.',
    createdAt: '2026-10-04',
  },
];

export const earlyWarningAlerts: EarlyWarningAlert[] = [
  {
    id: 'al_1',
    category: 'port_congestion',
    severity: 'critical',
    title: 'Severe Berth Congestion Warning at Paradip',
    message: 'Average waiting time at Paradip Mechanized Coal Berth reached 76.8 hours (14 vessels waiting, 92% berth utilization). Demurrage exposure estimated at $38,400 per shipment.',
    portOrRoute: 'Paradip Port',
    timestamp: '25 mins ago',
    actionRequired: 'Consider partial discharge at Gangavaram / Dhamra or adjust arrival laycan by +3 days.',
  },
  {
    id: 'al_2',
    category: 'market_entry_window',
    severity: 'warning',
    title: 'Market Entry Window Closing: Coking Coal Corridors',
    message: 'Australia to East Coast India freight rates have increased +2.1% this week. Q4 procurement window closing in 7 days before anticipated $29.10/MT rate peak.',
    portOrRoute: 'Newcastle → Vizag',
    timestamp: '1 hour ago',
    actionRequired: 'Lock short-term multiple-voyage contract (3 voyages) to fix rate at $26.80/MT.',
  },
  {
    id: 'al_3',
    category: 'vessel_idle',
    severity: 'warning',
    title: 'Vessel Idle Time Advisory: MV Ocean Pioneer',
    message: 'Expected turnaround delay at Paradip will cause 4.2 days of unproductive vessel idle time post-discharge before next cargo readiness.',
    portOrRoute: 'MV Ocean Pioneer (Panamax)',
    timestamp: '3 hours ago',
    actionRequired: 'Authorize repositioning to Vizag or book backhaul parcel to optimize voyage positioning.',
  },
  {
    id: 'al_4',
    category: 'weather_disruption',
    severity: 'info',
    title: 'Bay of Bengal Monsoon Sea State Advisory',
    message: 'Moderate depression forming in Central Bay of Bengal. Sailing speed reduction of 1.2 knots expected on Southern approaches.',
    portOrRoute: 'Bay of Bengal Trade Lane',
    timestamp: '5 hours ago',
    actionRequired: 'Incorporate 18 hours voyage buffer into laycan scheduling.',
  },
];

export const idleScenarios: IdleScenario[] = [
  {
    id: 'isc_1',
    vesselName: 'MV Ocean Pioneer',
    vesselType: 'Panamax',
    dischargePort: 'Paradip',
    expectedIdleDays: 4.5,
    dailyIdleCostUSD: 16500,
    totalIdleCostUSD: 74250,
    idleRisk: 'high',
    currentPosition: 'Paradip Anchorage',
    nextCargoLocation: 'Visakhapatnam (SAIL Ore Berth)',
    deadheadDistanceNM: 210,
    deadheadFuelCostUSD: 14200,
    recommendedRepositioning: 'Reposition vessel to Visakhapatnam immediately post-discharge',
    alternativeRoute: 'Vizag → Newcastle Coal Return',
    estimatedIdleReductionDays: 3.0,
    netSavingsUSD: 35300,
    reason: 'Repositioning 210 NM southward absorbs idle days into active positioning and captures spot iron ore parcel with minimal ballast steaming.',
  },
  {
    id: 'isc_2',
    vesselName: 'MV Bharat Gaurav',
    vesselType: 'Capesize',
    dischargePort: 'Gangavaram',
    expectedIdleDays: 2.0,
    dailyIdleCostUSD: 24500,
    totalIdleCostUSD: 49000,
    idleRisk: 'low',
    currentPosition: 'Gangavaram Port',
    nextCargoLocation: 'Port Hedland, Australia',
    deadheadDistanceNM: 3200,
    deadheadFuelCostUSD: 165000,
    recommendedRepositioning: 'Direct ballast voyage to Port Hedland under contract voyage #2',
    alternativeRoute: 'Australia → Dhamra Multi-Voyage Leg 2',
    estimatedIdleReductionDays: 1.5,
    netSavingsUSD: 36750,
    reason: 'Direct turnaround under 6-month multiple-voyage charter eliminates waiting and maintains contract TCE advantage.',
  },
  {
    id: 'isc_3',
    vesselName: 'MV Kalinga Express',
    vesselType: 'Supramax',
    dischargePort: 'Haldia',
    expectedIdleDays: 5.5,
    dailyIdleCostUSD: 14200,
    totalIdleCostUSD: 78100,
    idleRisk: 'high',
    currentPosition: 'Haldia River Berth',
    nextCargoLocation: 'Dhamra Port',
    deadheadDistanceNM: 140,
    deadheadFuelCostUSD: 8500,
    recommendedRepositioning: 'Short ballast shift to Dhamra for SMS Limestone loading',
    alternativeRoute: 'Dhamra → Paradip Coastal Feeder',
    estimatedIdleReductionDays: 4.0,
    netSavingsUSD: 48300,
    reason: 'Haldia riverine lock waiting eliminated by shifting vessel to Dhamra open-sea deepwater terminal.',
  },
];

export const recommendationHistory: RecommendationHistoryItem[] = [
  {
    id: 'rec_hist_1',
    date: '2026-10-04',
    cargoType: 'Coal',
    quantityMT: 75000,
    originPort: 'Newcastle, AU',
    destinationPort: 'Visakhapatnam',
    recommendedVessel: 'Panamax',
    recommendedStrategy: 'SHORT_TERM_3M',
    estimatedTotalCostUSD: 2010000,
    costPerMT: 26.80,
    estimatedSavingsUSD: 135000,
    reasons: [
      'Dual port compatibility confirmed (Newcastle 15.2m draft ✓ / Vizag 16.5m draft ✓)',
      'Freight forecast indicates +6.2% upward trend in spot rates over next 30 days',
      '3-Month Multi-Voyage contract secures 3 shipments at locked $26.80/MT rate',
      'Turnaround handling at Vizag (32k MT/day) achieves 2.3 days port stay vs 3.2 days at Paradip',
    ],
    status: 'accepted',
  },
  {
    id: 'rec_hist_2',
    date: '2026-10-02',
    cargoType: 'Coal',
    quantityMT: 165000,
    originPort: 'Hay Point, AU',
    destinationPort: 'Gangavaram',
    recommendedVessel: 'Capesize',
    recommendedStrategy: 'MEDIUM_TERM_6M',
    estimatedTotalCostUSD: 4257000,
    costPerMT: 25.80,
    estimatedSavingsUSD: 396000,
    reasons: [
      'Gangavaram 21.0m draft & 45k MT/day handling rate fully compatible with Capesize',
      '6-Month Medium-Term charter hedges 6 annual parcels against global bunker volatility',
      'Avoids lightering and demurrage costs totaling $140k per parcel',
    ],
    status: 'accepted',
  },
  {
    id: 'rec_hist_3',
    date: '2026-09-28',
    cargoType: 'Other Bulk Cargo',
    quantityMT: 55000,
    originPort: 'Mina Saqr, UAE',
    destinationPort: 'Dhamra',
    recommendedVessel: 'Supramax',
    recommendedStrategy: 'SPOT',
    estimatedTotalCostUSD: 880000,
    costPerMT: 16.00,
    estimatedSavingsUSD: 40000,
    reasons: [
      'Single spot voyage optimal for ad-hoc flux limestone consignment',
      'Low Arabian Sea freight rate volatility favors spot fixing',
    ],
    status: 'accepted',
  },
];

export const riskFactors: RiskFactor[] = [
  { name: 'Freight Market Volatility', level: 'medium', percentage: 58, description: 'Baltic Dry Index (BDI) firming with strong Q4 Asian import demand' },
  { name: 'East Coast Port Congestion', level: 'high', percentage: 76, description: 'High waiting times at Paradip and Haldia; berth occupancy > 88%' },
  { name: 'Bunker Fuel Price Shift', level: 'low', percentage: 32, description: 'VLSFO stable around $580-$595/MT across Singapore and Fujairah hubs' },
  { name: 'Weather / Monsoon Impact', level: 'medium', percentage: 46, description: 'Monsoon withdrawal transitions causing localized squalls in Bay of Bengal' },
  { name: 'Vessel Positioning & Idle Risk', level: 'medium', percentage: 52, description: 'Discharge delays create deadheading exposure if return cargo unallocated' },
  { name: 'Port Draft & Bathymetry Risk', level: 'low', percentage: 22, description: 'Tidal restrictions managed; Gangavaram/Dhamra deepwater berths available' },
  { name: 'AI Forecast Variance Risk', level: 'low', percentage: 16, description: 'Model confidence at 84% with tight 95% statistical confidence bounds' },
];

export const riskTrendData: RiskTrendPoint[] = [
  { date: 'Jul', freight: 35, congestion: 40, fuel: 25, weather: 65, vesselSupply: 30 },
  { date: 'Aug', freight: 42, congestion: 48, fuel: 28, weather: 58, vesselSupply: 28 },
  { date: 'Sep', freight: 52, congestion: 68, fuel: 30, weather: 48, vesselSupply: 34 },
  { date: 'Oct', freight: 58, congestion: 76, fuel: 32, weather: 46, vesselSupply: 52 },
];

export const forecastFactors: ForecastFactor[] = [
  { name: 'Indian Steel Production Surge', impact: 'positive', strength: 88, description: 'Crude steel capacity additions driving high coking coal import demand.' },
  { name: 'Australian Port Rail Maintenance', impact: 'positive', strength: 65, description: 'Temporary rail capacity bottlenecks at DBCT tightening loading throughput.' },
  { name: 'Bunker Benchmark Stability', impact: 'neutral', strength: 42, description: 'Crude oil rangebound, capping extreme bunker surcharge hikes.' },
  { name: 'Panamax Fleet Availability', impact: 'negative', strength: 55, description: 'Incoming ballast tonnage in Indian Ocean moderating extreme rate spikes.' },
];

export const marketInsights: MarketInsight[] = [
  {
    id: 'ins_1',
    title: 'Spot vs Multiple-Voyage Charter Disparity',
    description: 'Spot voyage rates are trading at an 11.8% premium over 3-month multi-voyage contracts. Locking multiple voyages now offers significant cost predictability.',
    type: 'opportunity',
    icon: 'TrendingUp',
  },
  {
    id: 'ins_2',
    title: 'Paradip Port Turnaround Bottleneck',
    description: 'Paradip mechanized berths are averaging 76.8 hours waiting time. Diverting Capesize parcels to Gangavaram or Dhamra saves up to $38k in demurrage per call.',
    type: 'warning',
    icon: 'AlertTriangle',
  },
  {
    id: 'ins_3',
    title: 'Vessel Positioning & Repositioning Yield',
    description: 'Ballasting Panamax vessels from Paradip to Vizag after discharge cuts vessel idle time by 3.0 days, capturing high-yield spot ore shipments.',
    type: 'trend',
    icon: 'Ship',
  },
  {
    id: 'ins_4',
    title: 'Q4 Dry Bulk Commodity Demand Acceleration',
    description: 'SAIL and RINL blast furnace ramp-ups are projected to increase overseas bulk coal procurement by +14% quarter-on-quarter.',
    type: 'info',
    icon: 'Info',
  },
];

export const reports: ReportInfo[] = [
  {
    id: 'rep_1',
    title: 'FreightIQ Strategic Chartering Decision Report: Q4-2026 Coal Corridor',
    type: 'Strategic Charter Advisory',
    route: 'Newcastle, AU → Paradip / Visakhapatnam',
    generatedDate: '2026-10-05',
    status: 'ready',
    summary: 'Executive procurement recommendation for 225,000 MT Coking Coal imports across Q4 2026. Proactive execution of a 3-Month Short-Term Multiple-Voyage Charter is recommended over spot fixing to capture $396,000 in landed procurement savings.',
    sections: [
      {
        heading: '1. Executive Decision Summary',
        content: 'System recommends transitioning from reactive spot chartering to a 3-Month Multiple-Voyage Charter (3 voyages of 75,000 MT via Panamax). This strategy locks the freight rate at $26.80/MT, mitigating projected spot rate surges to $29.10-$31.40/MT.',
      },
      {
        heading: '2. Dual Port Bathymetry & Constraints Validation',
        content: 'Loading Port (Newcastle): Permissible draft 15.2m, LOA 300m — fully compatible with Panamax laden draft (14.2m). Discharge Port (Visakhapatnam): Permissible draft 16.5m, handling rate 32,000 MT/day — turnaround estimated at 2.3 days with low demurrage exposure.',
      },
      {
        heading: '3. Cost Economics & Landed Cost Breakdown',
        content: 'Total Landed Cost under 3-Month Multi-Voyage: $6,030,000 ($26.80/MT) vs Spot Alternative: $6,426,000 ($28.56/MT). Net landed savings: $396,000. Bunker cost component: $1,260,000; Port dues: $255,000.',
      },
      {
        heading: '4. Idle Scenario Management & Repositioning Plan',
        content: 'Post-discharge at Visakhapatnam, vessels are scheduled for immediate backhaul positioning or direct turnaround voyage #2 to Newcastle, reducing expected idle time to under 1.5 days.',
      },
    ],
  },
];
